"""init schema without generated tsvector

Revision ID: 5af10c03069b
Revises: 
Create Date: 2025-11-05 20:18:40.764239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5af10c03069b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('city_slug', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("city_slug IS NULL OR city_slug ~ '^[a-z0-9-]+$'", name='ck_location_city_slug'),
    sa.CheckConstraint("country_code ~ '^[A-Z]{2}$'", name='ck_location_country_code_iso2'),
    sa.CheckConstraint('order_index >= 0', name='ck_location_order_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'city_slug', name='uq_location_country_city')
    )
    op.create_index('ix_location_city_slug', 'location', ['city_slug'], unique=False)
    op.create_index('ix_location_country_code', 'location', ['country_code'], unique=False)
    op.create_table('media_asset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(width IS NULL AND height IS NULL) OR (width > 0 AND height > 0)', name='ck_media_asset_dimensions_valid'),
    sa.CheckConstraint('file_size >= 0', name='ck_media_asset_file_size_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_asset_checksum'), 'media_asset', ['checksum'], unique=False)
    op.create_index('ix_media_asset_created_at', 'media_asset', ['created_at'], unique=False)
    op.create_index('ix_media_asset_mime_type', 'media_asset', ['mime_type'], unique=False)
    op.create_table('person_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_person_role_key', 'person_role', ['key'], unique=False)
    op.create_index('ix_person_role_order', 'person_role', ['order_index'], unique=False)
    op.create_table('project_style',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("key ~ '^[a-z0-9_]+$'", name='ck_project_style_key_slug'),
    sa.CheckConstraint('order_index >= 0', name='ck_project_style_order_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_project_style_key', 'project_style', ['key'], unique=False)
    op.create_index('ix_project_style_visible', 'project_style', ['visible'], unique=False)
    op.create_table('project_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("key ~ '^[a-z0-9_]+$'", name='ck_project_type_key_slug'),
    sa.CheckConstraint('order_index >= 0', name='ck_project_type_order_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_project_type_key', 'project_type', ['key'], unique=False)
    op.create_index('ix_project_type_visible', 'project_type', ['visible'], unique=False)
    op.create_table('location_i18n',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.Enum('EN', 'RU', 'TK', name='language_enum'), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'locale')
    )
    op.create_index('ix_location_i18n_locale', 'location_i18n', ['locale'], unique=False)
    op.create_table('media_asset_i18n',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.Enum('EN', 'RU', 'TK', name='language_enum'), nullable=False),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['media_asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'locale')
    )
    op.create_index('ix_media_asset_i18n_locale', 'media_asset_i18n', ['locale'], unique=False)
    op.create_table('person',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('photo_media_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9-]+$'", name='ck_person_slug_format'),
    sa.CheckConstraint('order_index >= 0', name='ck_person_order_nonneg'),
    sa.ForeignKeyConstraint(['photo_media_id'], ['media_asset.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_person_order', 'person', ['order_index'], unique=False)
    op.create_index('ix_person_published', 'person', ['is_published'], unique=False)
    op.create_index('ix_person_slug', 'person', ['slug'], unique=False)
    op.create_table('person_role_i18n',
    sa.Column('person_role_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.Enum('EN', 'RU', 'TK', name='language_enum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_role_id'], ['person_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_role_id', 'locale')
    )
    op.create_index('ix_person_role_i18n_locale', 'person_role_i18n', ['locale'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('cover_media_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('type_id', sa.UUID(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('completion', sa.Integer(), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9-]+$'", name='ck_project_slug_format'),
    sa.CheckConstraint('NOT is_published OR published_at IS NOT NULL', name='ck_project_published_has_date'),
    sa.CheckConstraint('area_m2 IS NULL OR area_m2 >= 0', name='ck_project_area_nonneg'),
    sa.CheckConstraint('completion IS NULL OR (completion BETWEEN 1850 AND EXTRACT(YEAR FROM now())::int + 2)', name='ck_project_completion_sane'),
    sa.CheckConstraint('completion IS NULL OR year IS NULL OR completion >= year', name='ck_project_completion_ge_year'),
    sa.CheckConstraint('year IS NULL OR (year BETWEEN 1850 AND EXTRACT(YEAR FROM now())::int + 2)', name='ck_project_year_sane'),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media_asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_id'], ['project_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_loc_pub_order', 'project', ['location_id', 'is_published', sa.text('order_index DESC')], unique=False)
    op.create_index('ix_project_pub_published_at_desc', 'project', ['is_published', sa.text('published_at DESC')], unique=False)
    op.create_index(op.f('ix_project_slug'), 'project', ['slug'], unique=True)
    op.create_index('ix_project_type_loc_pub_order', 'project', ['type_id', 'location_id', 'is_published', sa.text('order_index DESC')], unique=False)
    op.create_index('ix_project_type_pub_order', 'project', ['type_id', 'is_published', sa.text('order_index DESC')], unique=False)
    op.create_table('project_style_i18n',
    sa.Column('style_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.Enum('EN', 'RU', 'TK', name='language_enum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['project_style.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('style_id', 'locale'),
    sa.UniqueConstraint('style_id', 'locale', name='uq_project_style_i18n_style_locale')
    )
    op.create_index('ix_project_style_i18n_locale', 'project_style_i18n', ['locale'], unique=False)
    op.create_table('project_type_i18n',
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.Enum('EN', 'RU', 'TK', name='language_enum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['project_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('type_id', 'locale')
    )
    op.create_index('ix_project_type_i18n_locale', 'project_type_i18n', ['locale'], unique=False)
    op.create_table('person_i18n',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.Enum('EN', 'RU', 'TK', name='language_enum'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('position_title', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', 'locale'),
    sa.UniqueConstraint('person_id', 'locale', name='uq_person_i18n_person_locale')
    )
    op.create_index('ix_person_i18n_locale', 'person_i18n', ['locale'], unique=False)
    op.create_table('project_i18n',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.Enum('EN', 'RU', 'TK', name='language_enum'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subname', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'locale')
    )
    op.create_index('ix_project_i18n_locale', 'project_i18n', ['locale'], unique=False)
    op.create_index('ix_project_i18n_search', 'project_i18n', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('project_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('PHOTO', 'DRAWING', 'HERO', name='project_media_kind'), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('order_index >= 0', name='ck_project_media_order_nonneg'),
    sa.ForeignKeyConstraint(['media_id'], ['media_asset.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'media_id', 'kind', name='uq_project_media_unique')
    )
    op.create_index('ix_project_media_kind_order', 'project_media', ['project_id', 'kind', 'order_index'], unique=False)
    op.create_index('ix_project_media_media', 'project_media', ['media_id'], unique=False)
    op.create_index(
    'uq_project_media_single_hero',
    'project_media',
    ['project_id'],
    unique=True,
    postgresql_where=sa.text("kind::text = 'hero'")
)
    op.create_table('project_person_role',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('order_index >= 0', name='ck_project_person_role_order_nonneg'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['person_role.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'person_id', 'role_id')
    )
    op.create_index('ix_project_person_role_order', 'project_person_role', ['project_id', 'role_id', 'order_index'], unique=False)
    op.create_index('ix_project_person_role_person', 'project_person_role', ['person_id'], unique=False)
    op.create_table('project_style_link',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('style_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_id'], ['project_style.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'style_id')
    )
    op.create_index('ix_project_style_link_project', 'project_style_link', ['project_id'], unique=False)
    op.create_index('ix_project_style_link_project_order', 'project_style_link', ['project_id', 'style_id'], unique=False)
    op.create_index('ix_project_style_link_style', 'project_style_link', ['style_id'], unique=False)
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent;")

    # 2) функция — одной командой
    op.execute("""
        CREATE OR REPLACE FUNCTION project_media_enforce_single_hero()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
        IF NEW.kind = 'hero' THEN
            IF EXISTS (
            SELECT 1 FROM project_media
            WHERE project_id = NEW.project_id
                AND kind = 'hero'
                AND (id IS DISTINCT FROM NEW.id)
            ) THEN
            RAISE EXCEPTION 'project % already has a hero media', NEW.project_id
                USING ERRCODE = 'unique_violation';
            END IF;
        END IF;
        RETURN NEW;
        END$$;
        """)
    op.execute("DROP TRIGGER IF EXISTS trg_project_media_single_hero ON project_media;")
    op.execute("""
        CREATE TRIGGER trg_project_media_single_hero
        BEFORE INSERT OR UPDATE OF kind, project_id
        ON project_media
        FOR EACH ROW
        EXECUTE FUNCTION project_media_enforce_single_hero();
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_style_link_style', table_name='project_style_link')
    op.drop_index('ix_project_style_link_project_order', table_name='project_style_link')
    op.drop_index('ix_project_style_link_project', table_name='project_style_link')
    op.drop_table('project_style_link')
    op.drop_index('ix_project_person_role_person', table_name='project_person_role')
    op.drop_index('ix_project_person_role_order', table_name='project_person_role')
    op.drop_table('project_person_role')
    op.drop_index('uq_project_media_single_hero', table_name='project_media', postgresql_where=sa.text("kind = 'hero'"))
    op.drop_index('ix_project_media_media', table_name='project_media')
    op.drop_index('ix_project_media_kind_order', table_name='project_media')
    op.drop_table('project_media')
    op.drop_index('ix_project_i18n_search', table_name='project_i18n', postgresql_using='gin')
    op.drop_index('ix_project_i18n_locale', table_name='project_i18n')
    op.drop_table('project_i18n')
    op.drop_index('ix_person_i18n_locale', table_name='person_i18n')
    op.drop_table('person_i18n')
    op.drop_index('ix_project_type_i18n_locale', table_name='project_type_i18n')
    op.drop_table('project_type_i18n')
    op.drop_index('ix_project_style_i18n_locale', table_name='project_style_i18n')
    op.drop_table('project_style_i18n')
    op.drop_index('ix_project_type_pub_order', table_name='project')
    op.drop_index('ix_project_type_loc_pub_order', table_name='project')
    op.drop_index(op.f('ix_project_slug'), table_name='project')
    op.drop_index('ix_project_pub_published_at_desc', table_name='project')
    op.drop_index('ix_project_loc_pub_order', table_name='project')
    op.drop_table('project')
    op.drop_index('ix_person_role_i18n_locale', table_name='person_role_i18n')
    op.drop_table('person_role_i18n')
    op.drop_index('ix_person_slug', table_name='person')
    op.drop_index('ix_person_published', table_name='person')
    op.drop_index('ix_person_order', table_name='person')
    op.drop_table('person')
    op.drop_index('ix_media_asset_i18n_locale', table_name='media_asset_i18n')
    op.drop_table('media_asset_i18n')
    op.drop_index('ix_location_i18n_locale', table_name='location_i18n')
    op.drop_table('location_i18n')
    op.drop_index('ix_project_type_visible', table_name='project_type')
    op.drop_index('ix_project_type_key', table_name='project_type')
    op.drop_table('project_type')
    op.drop_index('ix_project_style_visible', table_name='project_style')
    op.drop_index('ix_project_style_key', table_name='project_style')
    op.drop_table('project_style')
    op.drop_index('ix_person_role_order', table_name='person_role')
    op.drop_index('ix_person_role_key', table_name='person_role')
    op.drop_table('person_role')
    op.drop_index('ix_media_asset_mime_type', table_name='media_asset')
    op.drop_index('ix_media_asset_created_at', table_name='media_asset')
    op.drop_index(op.f('ix_media_asset_checksum'), table_name='media_asset')
    op.drop_table('media_asset')
    op.drop_index('ix_location_country_code', table_name='location')
    op.drop_index('ix_location_city_slug', table_name='location')
    op.drop_table('location')
    op.execute("DROP TRIGGER IF EXISTS trg_project_media_single_hero ON project_media;")
    op.execute("DROP FUNCTION IF EXISTS project_media_enforce_single_hero;")


    # ### end Alembic commands ###
